import type { Metadata } from "next";
import { Inter, Markazi_Text } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const markazi = Markazi_Text({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={markazi.className}>{children}</body>
    </html>
  );
}
